"""
Schemas for proposal documents.
"""

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


class ProposalCreate(BaseModel):
    title: str = Field(..., min_length=1, max_length=255)
    body_json: dict[str, Any] = Field(default_factory=dict)
    status: str = Field(default="draft")


class ProposalUpdate(BaseModel):
    title: str | None = Field(None, min_length=1, max_length=255)
    body_json: dict[str, Any] | None = None
    status: str | None = None
    is_locked: bool | None = None


class ProposalSectionPlanItem(BaseModel):
    id: str = Field(..., min_length=1, max_length=80)
    label: str | None = Field(None, max_length=120)
    enabled: bool = True


class ProposalGenerateAIRequest(BaseModel):
    title: str | None = None
    language: str = Field(default="es", pattern="^(es|en)$")
    extra_instructions: str | None = None
    services_context: str | None = None
    proposal_objective: str | None = None
    estimated_timeline: str | None = None
    payment_conditions: str | None = None
    execution_conditions: str | None = None
    tone: str | None = Field(None, max_length=80)
    audience: str | None = Field(None, max_length=255)
    differentiators: str | None = Field(None, max_length=2000)
    section_plan: list[ProposalSectionPlanItem] = Field(default_factory=list)
    persist_context: bool = Field(default=True)
    user_api_key: str | None = Field(None, max_length=256)
    ai_provider: str | None = Field(None, pattern="^(openai|anthropic)$")


class ProposalResponse(BaseModel):
    id: int
    project_id: int
    organization_id: int
    version: int
    title: str
    body_json: dict[str, Any]
    status: str
    is_locked: bool
    created_by_id: int | None = None
    updated_by_id: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

    model_config = {"from_attributes": True}


class ProposalListResponse(BaseModel):
    items: list[ProposalResponse]
    total: int


class ProposalClientShareRequest(BaseModel):
    to_email: str | None = Field(None, description="Client destination email")
    quote_id: int | None = Field(None, description="Optional quote version to show in portal")
    access_expires_at: datetime | None = Field(
        None, description="Custom access expiration datetime (max 30 days)"
    )
    access_code: str | None = Field(
        None,
        min_length=4,
        max_length=16,
        description="Optional temporary key defined by sender; autogenerated if omitted",
    )
    message: str | None = Field(None, description="Optional custom message for the client")
    send_email: bool = Field(
        True,
        description="If false, generate client access link and code without sending email",
    )


class ProposalClientShareResponse(BaseModel):
    success: bool
    message: str
    public_url: str
    access_expires_at: datetime
    last_sent_at: datetime | None = None
    access_code: str | None = None
    sent_email: bool = True


class ProposalShareStatsResponse(BaseModel):
    proposal_id: int
    link_id: int | None = None
    status: str | None = None
    view_count: int = 0
    viewed_at: datetime | None = None
    last_sent_at: datetime | None = None
    decided_at: datetime | None = None
    decision_comment: str | None = None
    access_expires_at: datetime | None = None


class ProposalAssetUploadResponse(BaseModel):
    success: bool
    asset_type: Literal["logo", "cover"]
    asset_url: str
    asset_key: str
    body_json: dict[str, Any]


class ProposalClientVerifyRequest(BaseModel):
    access_code: str = Field(..., min_length=4, max_length=16)


class ProposalClientVerifyResponse(BaseModel):
    session_token: str
    expires_at: datetime
    proposal_status: str


class ProposalClientDecisionRequest(BaseModel):
    decision: Literal["accepted", "rejected", "revision_requested"]
    comment: str | None = Field(None, max_length=2000)


class ProposalClientPortalResponse(BaseModel):
    proposal_id: int
    proposal_title: str
    proposal_body_json: dict[str, Any]
    organization_name: str | None = None
    project_name: str
    client_name: str
    quote_id: int | None = None
    quote_version: int | None = None
    quote_total_client_price: str | None = None
    quote_currency: str | None = None
    decision_status: str
    decision_comment: str | None = None
    decided_at: datetime | None = None
    access_expires_at: datetime
