"""
Schemas for proposal documents.
"""
from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


class ProposalCreate(BaseModel):
    title: str = Field(..., min_length=1, max_length=255)
    body_json: Dict[str, Any] = Field(default_factory=dict)
    status: str = Field(default="draft")


class ProposalUpdate(BaseModel):
    title: Optional[str] = Field(None, min_length=1, max_length=255)
    body_json: Optional[Dict[str, Any]] = None
    status: Optional[str] = None
    is_locked: Optional[bool] = None


class ProposalGenerateAIRequest(BaseModel):
    title: Optional[str] = None
    language: str = Field(default="es", pattern="^(es|en)$")
    extra_instructions: Optional[str] = None
    services_context: Optional[str] = None
    proposal_objective: Optional[str] = None
    estimated_timeline: Optional[str] = None
    payment_conditions: Optional[str] = None
    execution_conditions: Optional[str] = None
    persist_context: bool = Field(default=True)


class ProposalResponse(BaseModel):
    id: int
    project_id: int
    organization_id: int
    version: int
    title: str
    body_json: Dict[str, Any]
    status: str
    is_locked: bool
    created_by_id: Optional[int] = None
    updated_by_id: Optional[int] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    model_config = {"from_attributes": True}


class ProposalListResponse(BaseModel):
    items: List[ProposalResponse]
    total: int


class ProposalClientShareRequest(BaseModel):
    to_email: Optional[str] = Field(None, description="Client destination email")
    quote_id: Optional[int] = Field(None, description="Optional quote version to show in portal")
    access_expires_at: Optional[datetime] = Field(None, description="Custom access expiration datetime (max 30 days)")
    access_code: Optional[str] = Field(
        None,
        min_length=4,
        max_length=16,
        description="Optional temporary key defined by sender; autogenerated if omitted",
    )
    message: Optional[str] = Field(None, description="Optional custom message for the client")
    send_email: bool = Field(
        True,
        description="If false, generate client access link and code without sending email",
    )


class ProposalClientShareResponse(BaseModel):
    success: bool
    message: str
    public_url: str
    access_expires_at: datetime
    last_sent_at: Optional[datetime] = None
    access_code: Optional[str] = None
    sent_email: bool = True


class ProposalClientVerifyRequest(BaseModel):
    access_code: str = Field(..., min_length=4, max_length=16)


class ProposalClientVerifyResponse(BaseModel):
    session_token: str
    expires_at: datetime
    proposal_status: str


class ProposalClientDecisionRequest(BaseModel):
    decision: Literal["accepted", "rejected", "revision_requested"]
    comment: Optional[str] = Field(None, max_length=2000)


class ProposalClientPortalResponse(BaseModel):
    proposal_id: int
    proposal_title: str
    proposal_body_json: Dict[str, Any]
    project_name: str
    client_name: str
    quote_id: Optional[int] = None
    quote_version: Optional[int] = None
    quote_total_client_price: Optional[str] = None
    quote_currency: Optional[str] = None
    decision_status: str
    decision_comment: Optional[str] = None
    decided_at: Optional[datetime] = None
    access_expires_at: datetime
